#!/bin/bash
# ============================================================
# DEPLOY KIT — setup.sh (beginner-friendly setup wizard)
# ------------------------------------------------------------
#   /bin/bash setup.sh
# Clean YES/NO questions with recommended defaults — a beginner
# can press Enter all the way and get a working config.
# Creates config.sh. Then run keygen.sh for SSH keys + GitHub
# copy-paste blocks.
# ============================================================

cd "$(dirname "${BASH_SOURCE[0]}")"
if [ -f config.sh ]; then
  echo "⚠️ config.sh already exists — to create a new one first: rm config.sh"
  echo "   (or edit it directly: nano config.sh)"
  exit 1
fi

ask() { read -rp "$1 [$2]: " v; echo "${v:-$2}"; }

# yesno: $1=question  $2=default (yes|no)  → returns 0=yes, 1=no
yesno() {
  local a d
  [ "$2" = "yes" ] && d="Y/n" || d="y/N"
  read -rp "$1 ($d): " a
  case "$a" in
    "" ) [ "$2" = "yes" ] && return 0 || return 1 ;;
    y|Y|yes|YES|Yes ) return 0 ;;
    * ) return 1 ;;
  esac
}

echo "============================================="
echo "  Deploy Kit — Setup Wizard"
echo "  * Answer YES/NO or paste values"
echo "  * Press Enter = recommended answer"
echo "  * No technical knowledge needed — hints on every step"
echo "============================================="

# ── 1. Server basics ──────────────────────────────
SERVER_USER=$(ask "Server login username (cPanel username)" "cpuser")
SERVER_HOST=$(ask "Server host or IP" "your-server.com")
SSH_PORT=$(ask "SSH port (cPanel = 22)" "22")
SITE_DOMAIN=$(ask "Live domain, without https://" "myapp.com")
APP_DIR=$(ask "App folder on the server (full path)" "/home/$SERVER_USER/myapp")
echo ""
echo "  📋 Copy from GitHub: open your repo → green Code button → SSH"
REPO_URL=$(ask "GitHub repo SSH URL (git@github.com:...)" "git@github.com:user/repo.git")
echo ""

# ── 2. App type (restart method auto-set) ────────
echo "  What kind of app is this?"
echo "    python (Django/Flask/FastAPI) | node | php | static | docker"
APP_TYPE=$(ask "App type" "python")
case "$APP_TYPE" in
  python) RESTART_METHOD="passenger"; WSGI_FILE="passenger_wsgi.py" ;;
  node)   RESTART_METHOD="passenger"; WSGI_FILE="passenger_wsgi.py" ;;
  php)    RESTART_METHOD="php";        WSGI_FILE="" ;;
  docker) RESTART_METHOD="docker";     WSGI_FILE="" ;;
  static) RESTART_METHOD="none";       WSGI_FILE="" ;;
  *)      RESTART_METHOD="passenger";  WSGI_FILE="" ;;
esac
echo "  (restart method auto-set: $RESTART_METHOD — change later in config.sh if needed)"
echo ""

# ── 3. Optional features (all YES/NO) ────────────
BUILD_CMD=""
if yesno "Do you need a build step? (e.g. npm run build)" no; then
  BUILD_CMD=$(ask "Paste your build command" "")
fi

DB_BACKUP="no"; DB_TYPE="mysql"; DB_HOST="localhost"
DB_USER=""; DB_PASS=""; DB_NAME=""
if yesno "Do you use a database?" no; then
  DB_TYPE=$(ask "DB type (mysql / postgres)" "mysql")
  DB_NAME=$(ask "DB name" "")
  DB_USER=$(ask "DB user" "")
  DB_PASS=$(ask "DB password (stays on the server, never committed)" "")
  if yesno "Backup the DB before every deploy? (recommended for production)" no; then
    DB_BACKUP="yes"
  fi
fi

MIGRATE_CMD=""
if yesno "Do you need database migrations on deploy? (e.g. alembic)" no; then
  if [ "$APP_TYPE" = "python" ]; then
    MIGRATE_CMD=$(ask "Migration command" '$PYTHON_BIN -m alembic upgrade head')
  else
    MIGRATE_CMD=$(ask "Paste your migration command" "")
  fi
fi

TELEGRAM_BOT_TOKEN=""; TELEGRAM_CHAT_ID=""
if yesno "Do you want Telegram alerts when a deploy finishes?" no; then
  echo "  📋 Get the token from @BotFather on Telegram"
  TELEGRAM_BOT_TOKEN=$(ask "Bot token" "")
  TELEGRAM_CHAT_ID=$(ask "Chat ID (ask @userinfobot after messaging the bot)" "")
fi

HEALTH_URL=""
if yesno "Do you want a health check after deploy? (recommended)" yes; then
  HEALTH_URL=$(ask "Health URL (Enter = https://$SITE_DOMAIN/)" "")
fi

# ── 4. Write config.sh (all keys — same as config.example.sh) ──
PYTHON_BIN="/home/$SERVER_USER/virtualenv/$SITE_DOMAIN/3.11/bin/python"
cat > config.sh <<EOF
# ── Deploy Kit config (generated by setup.sh — $(date '+%F %T')) ──
SERVER_USER="$SERVER_USER"
SERVER_HOST="$SERVER_HOST"
SSH_PORT="$SSH_PORT"
SITE_DOMAIN="$SITE_DOMAIN"
APP_DIR="$APP_DIR"
REPO_URL="$REPO_URL"

# ── Stack ──
APP_TYPE="$APP_TYPE"
PYTHON_BIN="$PYTHON_BIN"
NODE_BIN=""
BUILD_CMD="$BUILD_CMD"
MIGRATE_CMD="$MIGRATE_CMD"
RESTART_METHOD="$RESTART_METHOD"
WSGI_FILE="$WSGI_FILE"
DOCKER_COMPOSE=""
PHP_FPM_SERVICE=""

# ── Database ──
DB_BACKUP="$DB_BACKUP"
DB_TYPE="$DB_TYPE"
DB_HOST="$DB_HOST"
DB_USER="$DB_USER"
DB_PASS="$DB_PASS"
DB_NAME="$DB_NAME"

# ── Notifications ──
TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID"

# ── Health check (optional) ──
HEALTH_URL="$HEALTH_URL"

# ── Git / Advanced ──
DEPLOY_KEY=""
WORKSPACE_BASE="/home/$SERVER_USER/deploy-workspace"
TOGGLE_FLAG=""
SKIP_WHEN_FLAG=""
DEFAULT_BRANCH="main"
LOG_FILE=""
RSYNC_EXCLUDES=""
EOF

chmod 600 config.sh

# ── 5. Summary + next steps ──
echo ""
echo "✅ config.sh created!"
echo ""
echo "  ── Next step — SSH keys (1 command, copy-paste ready): ──"
echo "     /bin/bash keygen.sh"
echo ""
echo "  keygen.sh prints 3 copy-paste blocks for GitHub:"
echo "    1. Public key  → repo → Settings → Deploy keys"
echo "    2. Private key → repo → Settings → Secrets → SSH_PRIVATE_KEY"
echo "    3. Host/User/Port → Secrets (SERVER_HOST, SERVER_USER, SSH_PORT)"
echo ""

if yesno "Set up SSH keys now? (recommended — takes 1 minute)" yes; then
  echo ""
  /bin/bash keygen.sh
fi
