#!/bin/bash
# ============================================================
# DEPLOY KIT — setup.sh (interactive config generator)
# ------------------------------------------------------------
#   /bin/bash setup.sh
# Creates config.sh through questions & answers — a hint on
# every question (where to get each value). Mistakes are unlikely.
# ============================================================

cd "$(dirname "${BASH_SOURCE[0]}")"
if [ -f config.sh ]; then
  echo "⚠️ config.sh already exists — to create a new one first: rm config.sh"
  echo "   (or edit it directly: nano config.sh)"
  exit 1
fi

ask() { read -rp "$1 [$2]: " v; echo "${v:-$2}"; }

echo "============================================="
echo "  Deploy Kit — Setup (questions & answers)"
echo "  * Press Enter = use the default value"
echo "============================================="

SERVER_USER=$(ask "1/16 Server login user (cPanel username)" "cpuser")
SERVER_HOST=$(ask "2/16 Server IP or domain" "your-server.com")
SSH_PORT=$(ask "3/16 SSH port (cPanel = 22)" "22")
SITE_DOMAIN=$(ask "4/16 Live domain, without https://" "your-domain.com")
APP_DIR=$(ask "5/16 App folder on the server (full path)" "/home/$SERVER_USER/app")
REPO_URL=$(ask "6/16 Git repo SSH URL (GitHub → Code → SSH)" "git@github.com:user/repo.git")
APP_TYPE=$(ask "7/16 App type: python/node/php/static/docker" "python")
RESTART_METHOD=$(ask "8/16 Restart: passenger/touch/systemctl/docker/php/none" "passenger")
BUILD_CMD=$(ask "9/16 Build command (Node/static) — leave empty if none" "")
MIGRATE_CMD=$(ask "10/16 Migration command — leave empty if none" "$( [ "$APP_TYPE" = python ] && echo '$PYTHON_BIN -m alembic upgrade head' || echo '' )")
DB_BACKUP=$(ask "11/16 DB backup before migrate? yes/no" "no")
DB_NAME=$(ask "12/16 DB name (if backup is yes)" "")
DB_USER=$(ask "13/16 DB user (if backup is yes)" "")
TELEGRAM_TOKEN=$(ask "14/16 Telegram bot token (optional, you can leave it empty)" "")
TELEGRAM_CHAT=$(ask "15/16 Telegram chat ID (optional)" "")
HEALTH_URL=$(ask "16/16 Health check URL (optional — Enter = skip)" "")

cat > config.sh <<EOF
# ── Deploy Kit config (generated by setup.sh — $(date '+%F %T')) ──
SERVER_USER="$SERVER_USER"
SERVER_HOST="$SERVER_HOST"
SSH_PORT="$SSH_PORT"
SITE_DOMAIN="$SITE_DOMAIN"
APP_DIR="$APP_DIR"
REPO_URL="$REPO_URL"

# ── Stack ──
APP_TYPE="$APP_TYPE"
PYTHON_BIN="/home/$SERVER_USER/virtualenv/$SITE_DOMAIN/3.11/bin/python"
NODE_BIN=""
BUILD_CMD="$BUILD_CMD"
MIGRATE_CMD="$MIGRATE_CMD"
RESTART_METHOD="$RESTART_METHOD"
WSGI_FILE="passenger_wsgi.py"
DOCKER_COMPOSE=""
PHP_FPM_SERVICE=""

# ── Database ──
DB_BACKUP="$DB_BACKUP"
DB_TYPE="mysql"
DB_HOST="localhost"
DB_USER="$DB_USER"
DB_PASS=""
DB_NAME="$DB_NAME"

# ── Notifications ──
TELEGRAM_BOT_TOKEN="$TELEGRAM_TOKEN"
TELEGRAM_CHAT_ID="$TELEGRAM_CHAT"

# ── Health check (optional) ──
HEALTH_URL="$HEALTH_URL"

# ── Git / Advanced ──
DEPLOY_KEY=""
WORKSPACE_BASE="/home/$SERVER_USER/deploy-workspace"
TOGGLE_FLAG=""
SKIP_WHEN_FLAG=""
DEFAULT_BRANCH="main"
LOG_FILE=""
EOF

chmod 600 config.sh
echo ""
echo "✅ config.sh created!"
echo ""
echo "⚠️ Now edit the remaining details in it (not asked during setup):"
echo "   nano config.sh"
echo "   → DB_PASS (DB password)"
echo "   → PYTHON_BIN (if a different path)"
echo "   → WSGI_FILE / DOCKER_COMPOSE / PHP_FPM (according to your stack)"
echo ""
echo "Then test: /bin/bash auto_deploy.sh main"
