#!/bin/bash
# ============================================================
# DEPLOY KIT — setup-quick.sh (paste your config, no questions)
# ------------------------------------------------------------
#   /bin/bash setup-quick.sh
# Paste all your info at once (KEY=VALUE lines) →
# script creates config.sh. No questions asked.
# ============================================================

cd "$(dirname "${BASH_SOURCE[0]}")"
if [ -f config.sh ]; then
  echo "⚠️ config.sh already exists — to create a new one first: rm config.sh"
  echo "   (or edit it directly: nano config.sh)"
  exit 1
fi

echo "============================================================"
echo "  Deploy Kit — Quick Setup (paste your info)"
echo ""
echo "  Paste your values below (KEY=VALUE one per line),"
echo "  then press Ctrl+D. Optional lines can be left empty."
echo ""
echo "  Example:"
echo "    SERVER_USER=cpuser"
echo "    REPO_URL=git@github.com:user/repo.git"
echo "============================================================"
echo ""

# ── User se paste lo (Ctrl+D = khatam) ──
INPUT="$(cat)"

# ── Defaults ──
SERVER_USER="cpuser"
SERVER_HOST="your-server.com"
SSH_PORT="22"
SITE_DOMAIN="your-domain.com"
APP_DIR=""
REPO_URL=""
APP_TYPE="python"
RESTART_METHOD="passenger"
BUILD_CMD=""
MIGRATE_CMD=""
DB_BACKUP="no"
DB_NAME=""
DB_USER=""
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
HEALTH_URL=""

# ── Parse pasted KEY=VALUE lines ──
while IFS='=' read -r key val; do
  [ -z "$key" ] && continue
  case "$key" in
    SERVER_USER)   SERVER_USER="$val" ;;
    SERVER_HOST)   SERVER_HOST="$val" ;;
    SSH_PORT)      SSH_PORT="$val" ;;
    SITE_DOMAIN)   SITE_DOMAIN="$val" ;;
    APP_DIR)       APP_DIR="$val" ;;
    REPO_URL)      REPO_URL="$val" ;;
    APP_TYPE)      APP_TYPE="$val" ;;
    RESTART_METHOD) RESTART_METHOD="$val" ;;
    BUILD_CMD)     BUILD_CMD="$val" ;;
    MIGRATE_CMD)   MIGRATE_CMD="$val" ;;
    DB_BACKUP)     DB_BACKUP="$val" ;;
    DB_NAME)       DB_NAME="$val" ;;
    DB_USER)       DB_USER="$val" ;;
    TELEGRAM_BOT_TOKEN) TELEGRAM_BOT_TOKEN="$val" ;;
    TELEGRAM_CHAT_ID)   TELEGRAM_CHAT_ID="$val" ;;
    HEALTH_URL)    HEALTH_URL="$val" ;;
  esac
done <<< "$INPUT"

# ── Required check ──
if [ -z "$APP_DIR" ] || [ -z "$REPO_URL" ]; then
  echo "❌ APP_DIR and REPO_URL are required — paste these 2 and run again."
  exit 1
fi
[ "$APP_DIR" = "your-domain.com" ] && APP_DIR="/home/$SERVER_USER/app"

# ── Create config.sh ──
cat > config.sh <<EOF
# ── Deploy Kit config (generated by setup-quick.sh — $(date '+%F %T')) ──
SERVER_USER="$SERVER_USER"
SERVER_HOST="$SERVER_HOST"
SSH_PORT="$SSH_PORT"
SITE_DOMAIN="$SITE_DOMAIN"
APP_DIR="$APP_DIR"
REPO_URL="$REPO_URL"

# ── Stack ──
APP_TYPE="$APP_TYPE"
PYTHON_BIN="/home/$SERVER_USER/virtualenv/$SITE_DOMAIN/3.11/bin/python"
NODE_BIN=""
BUILD_CMD="$BUILD_CMD"
MIGRATE_CMD="$MIGRATE_CMD"
RESTART_METHOD="$RESTART_METHOD"
WSGI_FILE="passenger_wsgi.py"
DOCKER_COMPOSE=""
PHP_FPM_SERVICE=""

# ── Database ──
DB_BACKUP="$DB_BACKUP"
DB_TYPE="mysql"
DB_HOST="localhost"
DB_USER="$DB_USER"
DB_PASS=""
DB_NAME="$DB_NAME"

# ── Notifications ──
TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID"

# ── Health check (optional) ──
HEALTH_URL="$HEALTH_URL"

# ── Git / Advanced ──
DEPLOY_KEY=""
WORKSPACE_BASE="/home/$SERVER_USER/deploy-workspace"
TOGGLE_FLAG=""
SKIP_WHEN_FLAG=""
DEFAULT_BRANCH="main"
LOG_FILE=""
EOF

chmod 600 config.sh
echo ""
echo "✅ config.sh created!"
echo "   nano config.sh → edit remaining details (DB_PASS, PYTHON_BIN...)"
echo "   Then test: /bin/bash auto_deploy.sh main"
